apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "arax.fullname" . }}
  labels: 
    {{- include "arax.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "arax.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arax.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arax.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "arax.serviceAccountName" . }}
      initContainers:
        - name: {{ .Chart.Name }}-init-container
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
          command:
            - "/bin/bash"
            - "/scripts/download_database.sh"
          volumeMounts:
            - name: {{ include "arax.fullname" . }}-secret-volume
              mountPath: "/etc/ssh-key"
            - name: {{ include "arax.fullname" . }}-configs-volume
              mountPath: "/configs"
            - name: {{ include "arax.fullname" . }}-scripts-volume
              mountPath: "/scripts"
            - name: {{ include "arax.fullname" . }}-pvc
              mountPath: /databases
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/bash"
            - "/scripts/start_app.sh"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ include "arax.fullname" . }}-pvc
              mountPath: /mnt/data/orangeboard/databases/
            - name: {{ include "arax.fullname" . }}-configs-volume
              mountPath: /configs
            - name: {{ include "arax.fullname" . }}-scripts-volume
              mountPath: /scripts
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "arax.fullname" . }}-secret-volume
          secret:
            secretName: {{ include "arax.fullname" . }}-secret
            defaultMode: 0400
        - name: {{ include "arax.fullname" . }}-scripts-volume
          configMap:
            name: {{ include "arax.fullname" . }}-scripts
            defaultMode: 0755
        - name: {{ include "arax.fullname" . }}-configs-volume
          configMap:
            name: {{ include "arax.fullname" . }}-configs
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: {{ include "arax.fullname" . }}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 200Gi
